function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 30-May-2019 09:45:24

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',3,'Parent',axes1);
set(plot1(1),'DisplayName','SCSA-C','Marker','o');
set(plot1(2),'DisplayName','Savitzky-Golay','Marker','x');
set(plot1(3),'DisplayName','EMD-IT','Marker','*');

% Create xlabel
xlabel('Number of Samples');

% Create title
title('Blocks');

% Create ylabel
ylabel('SNR after denoising');

box(axes1,'on');
% Create legend
legend(axes1,'show');

